# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'

  # Pods for Weight


  target 'WeightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeightUITests' do
    # Pods for testing
  end

end
